services:
  mysql-prod:
    image: mysql:8.3
    container_name: parkingsystem-db-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: prod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  mysql-test:
    image: mysql:8.3
    container_name: parkingsystem-db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data_prod:
  mysql_data_test:


