services:

  db:
    image: mysql:8.0
    container_name: parkingsystem-db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: prod
    ports:
      - "3306:3306"
    networks:
      - parkingsystem-network
    volumes:
      - db-data:/var/lib/mysql

  dbtest:
    image: mysql:8.0
    container_name: parkingsystem-dbtest
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: test
    ports:
      - "3307:3307"
    networks:
      - parkingsystem-network
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: maven:3.8.5-openjdk-8
    container_name: parkingsystem-app
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: bash -c "mvn clean package && java -cp target/classes com.parkit.parkingsystem.App"
    depends_on:
      - db
    networks:
      - parkingsystem-network

networks:
  parkingsystem-network:
    driver: bridge

volumes:
  db-data: