bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-cache
      url: /api/.*
      rate-limits:
        - bandwidths:
            - capacity: 20
              time: 1
              unit: minutes